steps:
  - name: 'node:22'
    entrypoint: 'npm'
    args:
      - 'install'
  - name: 'gcr.io/graffiticode/firebase'
    entrypoint: 'npm'
    args:
      - 'test'
      - '-w'
      - 'packages/api'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/graffiticode/api:$COMMIT_SHA'
      - '-f'
      - 'configs/Dockerfile.api.yaml'
      - '.'
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - 'gcr.io/graffiticode/api:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - graffiticode-api
      - '--platform=managed'
      - '--no-traffic'
      - '--image=gcr.io/graffiticode/api:$COMMIT_SHA'
      - >-
        --labels=commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - 'gcr.io/graffiticode/api:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
substitutions:
  _DEPLOY_REGION: us-central1
tags:
  - graffiticode-api
